exports.studentsListPage = function(slist, d){  // slist -> Lista de Alunos, d -> data
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Compositores List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by GBENGWEB2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.studentFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Data de Obito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>

                
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.studentFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${a.bio}"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${a.dataNasc}"/>
                        <label>Data de Obito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${a.dataObito}"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${a.periodo}"/>
                    </fieldset>


                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.studentPage = function( compositores, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositores.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositores.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositores.nome}</li>
                    <li><b>Bio: </b> ${compositores.bio}</li>
                    <li><b>Data de Nascimento: </b> ${compositores.dataNasc}</li>
                    <li><b>Data de Obito: </b> ${compositores.dataObito}</li>
                    <li><b>Periodo: </b> ${compositores.periodo}</li>

                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <address>Gerado por GB::GBEngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}



// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `

    <html>
    <head>
        <title>Error</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
            <p>Error Page</p>
            </header>

            <div class="w3-container">
            <p>${d}: Error: ${errorMessage}</p>
            </div>
            </div>
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>

    `
}



//---------------------------------


// Function to generate the list of periodos page
exports.periodosListPage= function(periodos, date) {
    pagHTML = `
  <!DOCTYPE html>
  <html lang="en">
  <html>
  <head>
      <title>Periodos</title>
      <meta charset="utf-8"/>
      <link rel="icon" href="favicon.png"/>
      <link rel="stylesheet" href="w3.css"/>
  </head>
  <body>
  <div class="w3-card-4">

      <header class="w3-container w3-teal">
          <h1>Compositores List
          <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
          </h1>
          
      </header>

      <div class="w3-container">
          <table class="w3-table-all">
              <tr>
                  <th>Id</th><th>Name</th>
                  <th>Actions</th>
              </tr>
      `
for(let i=0; i < periodos.length ; i++){
pagHTML += `
      <tr>
          <td>${periodos[i].periodoID}</td>
          <td>
              <a href="/compositores/${periodos[i].periodoID}">
                  ${periodos[i].periodonome}
              </a>
          </td>
          <td>
              [<a href="/compositores/edit/${periodos[i].periodoID}">Edit</a>][<a href="/compositores/delete/${periodos[i].periodoID}">Delete</a>]
          </td>
      </tr>
`
}

pagHTML += `
    <footer class="w3-container w3-teal">
    <address>Gerado por galuno::RPCW2022 em ${date} - [<a href="/compositores">Voltar</a>]</address>
</footer>
</div>
</body>
</html>
    `;
  
    return pagHTML;
  }
  
  // Function to generate the page for a specific periodo
function periodoPage(periodo, date) {
    let html = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Periodo - ${periodo.periodo}</title>
    <style>
      /* Add styles for detailed information display */
    </style>
  </head>
  <body>
    <h1>Periodo: ${periodo.periodo} - ${date}</h1>
    <p>Detalhes do periodo ${periodo.periodo}...</p>
  </body>
  </html>
    `;
  
    return html;
  }
  
  // Function to generate the page for composers filtered by periodo
  function compositoresByPeriodoPage(compositores, date, periodo) {
    let html = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compositores do Periodo - ${periodo}</title>
    <style>
      /* Add styles for tables, headings, etc. */
    </style>
  </head>
  <body>
    <h1>Compositores do Periodo: ${periodo} - ${date}</h1>
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Nascimento</th>
          <th>Falecimento</th>
        </tr>
      </thead>
      <tbody>
    `;
  
    // Loop through compositores data and generate table rows
    for (let compositor of compositores) {
      html += `
        <tr>
          <td><span class="math-inline">\{compositor\.id\}</td\>
  <td\></span>{compositor.nome}</td>
          <td><span class="math-inline">\{compositor\.nascimento\}</td\>
  <td\></span>{compositor.falecimento}</td>
        </tr>
      `;
    }
  
    html += `
      </tbody>
    </table>
  </body>
  </html>
    `;
  
    return html;
  }